version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    registry-urls:
      - "https://registry.npmjs.org"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
